### ISSUE TITLE
PHP 8.x support

### ISSUE THREAD

**Issue by liborm85** [idmarinas/tracy-twig-bar#1]
PHP 8 was supported in version 0.1.0 (see [0.1.0/composer.json](https://github.com/idmarinas/tracy-twig-bar/blob/0.1.0/composer.json#L19)) and version 0.2.0 doesn't support PHP 8 (see [0.2.0/composer.json](https://github.com/idmarinas/tracy-twig-bar/blob/0.2.0/composer.json#L19)).
Is there a reason for that? Would it be possible to add support PHP 8.0 and 8.1?

**Comment by idmarinas** [comment]
I have not checked compatibility with PHP version 8.
I will check and add compatibility if there are no problems.

**Comment by idmarinas** [comment]
I release version 0.3.0 with compatibility with PHP 8.0 and 8.1

I use Rector for check code.
